const locations = {
  "1": "pitcher",
  "15": "off the mound on the third base side",
  "13": "off the mound on the first base side",
  "1S": "just off the plate toward the mound",
  "2": "in front of home plate",
  "23": "just off the plate toward first",
  "2F": "behind home plate",
  "25F": "foul territory halfway to third",
  "23F": "foul territory halfway to first",
  "25": "just off the plate toward third",
  "3": "first",
  "3S": "on the grass down the first base line",
  "34": "between first and second",
  "34S": "on the grass betwen first and second",
  "34D": "behind first and second",
  "3D": "behind first",
  "4": "second",
  "4S": "on the grass toward second",
  "4MD": "behind second and short",
  "4M": "up the middle",
  "4MS": "on the grass behind the mound",
  "4D": "behind second",
  "5": "third",
  "5S": "down the third base line just in front of the bag",
  "56": "between third and short",
  "56S": "on the grass to third",
  "5D": "behind third",
  "56D": "behind third and short",
  "6": "short",
  "6S": "on the grass to short",
  "6D": "behind short",
  "6MD": "behind second and short",
  "6M": "up the middle",
  "6MS": "on the grass behind the mound",
  "7": "left field",
  "78XD": "very deep left center field",
  "7L": "down the left field line",
  "7LD": "deep down the left field line",
  "7LS": "down the left field line",
  "7D": "deep left field",
  "7S": "shallow right field",
  "78S": "shallow right center field",
  "78": "left center field",
  "78D": "deep left center field",
  "8": "center field",
  "8D": "deep center field",
  "89": "right center field",
  "89D": "deep right center field",
  "89XD": "deep right fenter field",
  "8XD": "very deep center field",
  "8S": "shallow center field",
  "89S": "shallow right center field",
  "9": "right field",
  "9D": "deep right field",
  "9LD": "deep right field line",
  "9S": "shallow right field",
  "9LS": "shallow right field down the line",
  "9L": "down the right field line",
};
